name: hancheng-dl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch-cuda=12.4
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - ipykernel
  - pytest
  - matplotlib
  - jupyter
  - torchmetrics
  - scikit-learn
  - torchinfo
  - ruff
  - black
