name: hancheng-dl
channels:
  - conda-forge
dependencies:
  - python=3.11
  - torchaudio
  - pytorch
  - torchvision
  - numpy
  - pandas
  - ipykernel
  - pytest
  - matplotlib
  - jupyter
  - torchmetrics
  - scikit-learn
  - torchinfo
  - ruff
  - black
prefix: /Users/hanchengdong/miniforge3/envs/hancheng-dl
